# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Market' do

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'MJRefresh', '~> 3.1.7'

  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Market

  target 'MarketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarketUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
